import { defineConfig } from "react-doctor/api"

export default defineConfig({
  ignore: {
    rules: ["react-doctor/no-danger"],
    files: [
      "node_modules/**",
      ".next/**",
      ".agents/**",
      "next-env.d.ts",
      ".codegraph/**",
      ".cursor/**",
      ".vscode/**",
      ".github/**",
      ".ai/**",
      "tsconfig.tsbuildinfo",
      ".gga",
      ".env.example",
      "pnpm-workspace.yaml",
      "components/ui/**",
      "components/shared/AiCopyButton.tsx",
      "components/shared/DirectusImage.tsx",
      "components/shared/MaterialIcon.tsx",
      "components/shared/PreviewBanner.tsx",
      "components/shared/QrCode.tsx",
      "components/shared/Share.tsx",
      "components/shared/InfiniteScroll.tsx",
      "components/shared/PullToRefresh.tsx",
      "components/shared/SafeHtml.tsx",
      "components/shared/JsonViewer.tsx",
      "components/shared/Toc.tsx",
      "components/shared/StatusIndicator.tsx",
      "components/shared/ThemeToggle.tsx",
      "components/shared/PhoneInput.tsx",
      "components/shared/Typography.tsx",
      "components/shared/audio/**",
    ],
  },
})
