blank_issues_enabled: true
contact_links:
  - name: 📖 Documentación
    url: https://github.com/JesusOmarDev1/bgl-cms-app/blob/main/README.md
    about: Consultá el README para instrucciones de uso y referencia.
